package Interfaz;


import com.opencsv.exceptions.CsvValidationException;
import java.io.File;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import simulacionso.Documento;
import simulacionso.FileHandling;
import simulacionso.GestorUsuarios;
import simulacionso.Nodo;
import simulacionso.Usuario;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


public class UI_new extends javax.swing.JFrame {

    /**
     * Creates new form UI_new
     */
    
    public static File selectedFile;
    GestorUsuarios gu = new GestorUsuarios();
    DefaultListModel<Object> modeloLista = new DefaultListModel<>();
    private long tiempoInicio = System.currentTimeMillis();
    private JTabbedPane tabbedPane = new JTabbedPane();
//    
    public UI_new() {
        

        initComponents();
    }
    
    public int preguntarAccion() {
        // Array de opciones
        Object[] opciones = {"Sí", "No"};

        // Pregunta al usuario
        int respuesta = JOptionPane.showOptionDialog(
                null,
                "¿Deseas Elminar este usuario?",
                "Eliminar Usuario",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones,
                opciones[0]);

        return respuesta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cargarArchivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cargarArchivo.setText("Cargar Archivo");
        cargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(cargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 130, -1));

        jLabel1.setText("Cargue un archivo para poder ver el listado de usuarios");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarArchivoActionPerformed
        // TODO add your handling code here:
    
         JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(null);
        
        if (result == JFileChooser.APPROVE_OPTION) {
                    selectedFile = fileChooser.getSelectedFile();
                    String filePath = selectedFile.getPath();
                    
                    try{
                        gu.setUsuarios(FileHandling.readFile(selectedFile));
                    }catch(IOException | CsvValidationException e){
            e.printStackTrace();
        }
//                    System.out.println("Selected file path: " + filePath);
             boolean flag = true;
        
             
             
             String[] userNames = new String[gu.getUsuarios().size()];
           
            Nodo temp = gu.getUsuarios().getpFirst();
//            Usuario user = (Usuario) temp.getInfo()
            
           for (int i = 0; i < userNames.length; i++) {
                
               if (temp.getInfo() instanceof Usuario) {
                    
                    Usuario auxOne = (Usuario) temp.getInfo();
                    
                    userNames[i] = (String) auxOne.getNombre();
                    
                    temp = temp.getpNext();
            
                }
            }
           
           
            
//            while(temp != null){
//                modeloLista.addElement(temp.getInfo());
//                temp = temp.getpNext();
//                
//            }
            
            jList1.setListData(userNames);
        jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

//            JScrollPane scrollPane = new JScrollPane(userList);

            jList1.addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {
                    if (!e.getValueIsAdjusting()) {
                        
                        // Acciones que deseamos realizar cuando se selecciona un usuario
                        
                        
                        
                        String selectedUser = jList1.getSelectedValue();
                        
                        int respuesta = preguntarAccion();

        // Verificar la respuesta del usuario
        
        
        if (respuesta == JOptionPane.YES_OPTION) {
             
            // Eliminamos Usuario
            
              Nodo aux = gu.getUsuarios().getpFirst();
        
        if(aux.getInfo() instanceof Usuario){
            Usuario doc = (Usuario)aux.getpNext().getInfo();
            
            if(doc.getNombre().equals(selectedUser)){
                aux = aux.getpNext().getpNext();
            }
            else{
                aux = aux.getpNext();
            }
                
                
            
            
        }
            
           
                // Agrega más casos según sea necesario
            }
            
        

        
            
            // Lógica para el caso 'Sí'
         else if (respuesta == JOptionPane.NO_OPTION || respuesta == JOptionPane.CLOSED_OPTION) {
            System.out.println("El usuario seleccionó 'No' o cerró la ventana");
            // Lógica para el caso 'No' o si la ventana se cerró
        }
                        
                        
                        int hashCode = selectedUser.hashCode();
                       
                        Nodo aux = gu.getUsuarios().getpFirst();
                       
                        System.out.println("Usuario seleccionado: " + selectedUser + "hashCode = " + hashCode);
                        
                        while(aux != null){
                           
                            if(aux.getInfo() instanceof Usuario){
                           
                                Usuario temp = (Usuario)aux.getInfo();
                           
                                if (selectedUser.equals(temp.getNombre())){
                               
                                    System.out.println("Usuario seleccionado: " + temp.getNombre() + "hashCode = " + hashCode);
                               VentanaUsuario ventanaCarga = new VentanaUsuario(temp, gu, tiempoInicio);
                                ventanaCarga.setVisible(true);
//                                ventanaCarga.setVisible(true);
                                break;
                           } else {
                               aux = aux.getpNext();
                           }
                            
                       }
                       }
                    }                        
                }
                
            });
             
             
        JOptionPane.showMessageDialog(null, "Archivo cargado exitosamente!\n A continuación puede seleccionar usuarios para realizar operaciones");
                }
        
        
       
        
        
        
    
    }//GEN-LAST:event_cargarArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
//            jList1.setVisible(true);
            public void run() {
                            
                new UI_new().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargarArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
